# Generated by Django 3.2.7 on 2021-09-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=12)),
                ('IsActive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'master',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=25)),
                ('Pincode', models.CharField(max_length=6)),
                ('Address', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'userprofile',
            },
        ),
    ]
