# Generated by Django 3.2.7 on 2021-09-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0005_alter_contact_country'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
