# Generated by Django 3.2.7 on 2021-10-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0006_alter_contact_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ContactImage',
            field=models.FileField(default='default.png', upload_to='users/contact_images/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ProfileImage',
            field=models.FileField(default='default.png', upload_to='users/'),
        ),
    ]
